export const Colors = {
  BACKGROUND_DAY: '#F7F9FB',
  GRAY_LIGHT: '#CACAD6',
  GRAY_DARK: '#9999A5',
  GRAY_MATERIAL_LIGHT: '#CFCFCF',
  GRAY_MATERIAL_DARK: '#707070',
  GREEN_LIGHT: '#D7FFD9',
  GREEN_DARK: '#75A478',
  BLACK_LIGHT: '#2C2C2E',
};
